version: '3.8'
services:
  # webapp:
  #   container_name: involta_web
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redis-stack
  redis-stack:
    container_name: involta_redis
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    mem_limit: 500M
    environment:
      - REDIS_INSIGHT=true

